// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {context} from '../models';

export function CreatePassword(arg1:services.CreatePasswordRequest):Promise<void>;

export function DeletePassword(arg1:number):Promise<void>;

export function ExecuteCommand(arg1:string):Promise<any>;

export function ExpandWindow(arg1:number):Promise<void>;

export function GenerateAndSavePassword(arg1:services.CreatePasswordRequest):Promise<string>;

export function GeneratePassword():Promise<string>;

export function GetPassword(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function HideSpotlight():Promise<void>;

export function ImportPasswordFromCSV(arg1:string):Promise<number>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function LockApp():Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SearchPasswords(arg1:string):Promise<Array<services.PasswordEntryResponse>>;

export function SetWindowCollapsed():Promise<void>;

export function SetWindowExpanded():Promise<void>;

export function SetupMasterPassword(arg1:string,arg2:string):Promise<void>;

export function ShowSpotlight():Promise<void>;

export function TestConnection():Promise<string>;

export function TestToggle():Promise<void>;

export function ToggleWindow():Promise<void>;

export function ToggleWindowVisibility():Promise<void>;

export function UnlockApp(arg1:string):Promise<void>;
