// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function CreatePassword(arg1:main.CreatePasswordRequest):Promise<void>;

export function DeletePassword(arg1:number):Promise<void>;

export function GenerateAndSavePassword(arg1:main.CreatePasswordRequest):Promise<string>;

export function GeneratePassword():Promise<string>;

export function GetPassword(arg1:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportPasswordFromCSV(arg1:string):Promise<number>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function LockApp():Promise<void>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function SearchPasswords(arg1:string):Promise<Array<main.PasswordEntryResponse>>;

export function SetupMasterPassword(arg1:string,arg2:string):Promise<void>;

export function UnlockApp(arg1:string):Promise<void>;
