// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatePassword(arg1) {
  return window['go']['main']['App']['CreatePassword'](arg1);
}

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function GenerateAndSavePassword(arg1) {
  return window['go']['main']['App']['GenerateAndSavePassword'](arg1);
}

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function GetPassword(arg1) {
  return window['go']['main']['App']['GetPassword'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportPasswordFromCSV(arg1) {
  return window['go']['main']['App']['ImportPasswordFromCSV'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function LockApp() {
  return window['go']['main']['App']['LockApp']();
}

export function OnShutdown(arg1) {
  return window['go']['main']['App']['OnShutdown'](arg1);
}

export function SearchPasswords(arg1) {
  return window['go']['main']['App']['SearchPasswords'](arg1);
}

export function SetupMasterPassword(arg1, arg2) {
  return window['go']['main']['App']['SetupMasterPassword'](arg1, arg2);
}

export function UnlockApp(arg1) {
  return window['go']['main']['App']['UnlockApp'](arg1);
}
